apiVersion: v1
kind: Service
metadata:
  name: role-manager-service
spec:
  selector:
    app: role-manager  # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80    # The port on which your service will be exposed
      targetPort: 5000  # The port where the container listens
  type: LoadBalancer  # If using a cloud provider (e.g., AWS, GCP)
